# Generated by Django 5.2.4 on 2026-01-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_calories_post_carbs_post_fat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="해시태그"
            ),
        ),
    ]
