# Generated by Django 6.0 on 2025-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('코미디', '코미디'), ('드라마', '드라마'), ('SF', 'SF'), ('스릴러', '스릴러'), ('로맨스', '로맨스'), ('애니메이션', '애니메이션'), ('다큐멘터리', '다큐멘터리'), ('호러', '호러'), ('판타지', '판타지')], max_length=50),
        ),
    ]
