# Generated by Django 5.2.10 on 2026-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_alter_review_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="review",
            name="is_tmdb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="poster_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="tmdb_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="review",
            name="vote_average",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
