# Generated by Django 5.2.10 on 2026-01-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_review_author_alter_review_id_comment_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
